[package]
name = "BlockChain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "mining_OPT"
harness = false


[lib]
name = "block_chain"
path = "src/block_chain/mod.rs"